name: CtPaTown
favicon: null
layout_spectrum: 0.49939
typography_spectrum: 0.50618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002052'
    - '#0066ae'
    - '#d3ffff'
    - '#4ebae4'
    - '#b6661a'
  brandStrength: 0.625
  lightness: 0.7406921715009958
  saturation: 0.7382744692731649
  rhythmicContrast: 0.13959737587720156
purpose: []
