name: CtPaTown
favicon: null
layout_spectrum: 0.3911533919163048
typography_spectrum: 0.5831549309659749
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.21450852206908166
  lightness: 0.7406921715009958
  saturation: 0.7382744692731649
  rhythmicContrast: 0.13959737587720156
purpose: []
