name: Ct Pa Town
favicon: null
layout_spectrum: 0.49939
typography_spectrum: 0.50618
title: Welcome to Historic Ct Pa Town
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#002052'
    - '#0066ae'
    - '#d3ffff'
    - '#4ebae4'
    - '#b6661a'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
